# HASHERS

Entalpic:
  shorten_hash: False

PDD:
  cutoff: 100

# SimpleComposition:

# SIMILARITY

eqv2:
  threshold: 0.999
  trained: True
  cpu: False
  load_from_hf: True
  agg_type: sum

pymatgen:
  tolerance: 0.01
